### ISSUE TITLE
How to perform an analysis using just summary statistics

### ISSUE THREAD

**Issue by llpesce** [omerwe/S-PCGC#6] opened 2024-02-06 17:15 UTC
I apologize for my obtusity, but I Can't figure out from the manual how to actually analyze my data.
I have, let's say, two summary statistics. I do not have access to the subject left genotypes or phenotypes. Just the summary statistics (and they were done with Regenie too). 

I can build an LD panel from 1000 G (I am a bit confused regarding whether I need to select good SNPs since the summary stats is already seriously filtered) but how to I turn a summary statistics from Regenie into the one that would work for you? 

Would it be correct to say that all I need is to preprocess it with LDSC tools? specifically pass them through munge_sumstats.py  and then into S-PCGA?

Sincerely

**Comment by omerwe** [comment] 2024-02-11 11:27
Indeed, the framework is similar to the one in LDSC, and we recommend using a similar preprocessing framework as for LDSC.

**Comment by llpesce** [comment] 2024-02-15 18:21
I am working from the example into using the code with my data. I downloaded 1000 G, removed biallelics, double entries, set an all european panel. I set a MAF at .01 and I turned it into a bed file and computed allele frequencies. 
then I tried to run step 2
#run pcgc_sync.py to collect annotations details
python pcgc_sync.py \
--annot-chr baselineLD_v2.2/baselineLD. \
--frqfile-chr 1000G/1000G.EUR.QC. \
--out baselineLD_v2.2/baselineLD

And this happens
Traceback (most recent call last):
  File "/projects/b1137/Diabetic_retinopathy/GeneticCorrelation/S-PCGC/S-PCGC/pcgc_sync.py", line 140, in <module>
    df_sync, df_overlap, df_overlap_common = pcgc_sync2(args)
  File "/projects/b1137/Diabetic_retinopathy/GeneticCorrelation/S-PCGC/S-PCGC/pcgc_sync.py", line 90, in pcgc_sync2
    df_sync, df_overlap, df_overlap_common = collect_annotations_chr_info(annot_fname, df_frq, min_annot)
  File "/projects/b1137/Diabetic_retinopathy/GeneticCorrelation/S-PCGC/S-PCGC/pcgc_sync.py", line 36, in collect_annotations_chr_info
    raise ValueError('Not all SNPs in the annotations file have MAFs')
ValueError: Not all SNPs in the annotations file have MAFs

I sm decreasing my MAF filtering, but there is only so much I am willing to reduce the MAF and believe the R^2. Is there a way to tell the code to accept that it can't match all of them and live with it?

**Comment by llpesce** [comment] 2024-02-15 18:23
I really only want to compute heritability and genetic correlations at this point, without exploring (yet) annotations.

**Comment by omerwe** [comment] 2024-02-25 10:24
Hi, the problem is not that some SNPs have low MAFs. The problem is that some SNPs have no MAF **information**. Hence, S-PCGC doesn't know how to handle these SNPs. If you don't think these SNPs are important, you're welcome to remove them from the annotation files all together...

Hope this helps, please let me know if not!

**Comment by omerwe** [comment] 2024-03-10 10:09
Closing this issue, feel free to reopen if needed. Thanks!

**Closed as completed by omerwe** 2024-03-10 10:09 UTC
